import { createAdminClient } from '@/lib/supabase/server-admin'
import Link from 'next/link'
import MonthSelect from '@/components/admin/attendance/MonthSelect'
import { autoGenerateDraftPayslips } from '@/lib/actions/admin/payslips'
import type { PayslipRow } from '@/lib/types/database'

function formatRupiah(n: number) {
  return new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(n)
}

const STATUS_LABEL: Record<string, string> = {
  draft: 'Draft',
  sent: 'Terkirim',
  paid: 'Dibayar',
}
const STATUS_COLOR: Record<string, string> = {
  draft: 'bg-gray-100 text-gray-500',
  sent: 'bg-blue-100 text-blue-700',
  paid: 'bg-green-100 text-green-700',
}

export default async function PayslipsPage({
  searchParams,
}: {
  searchParams: Promise<{ month?: string; status?: string }>
}) {
  const { month, status } = await searchParams
  const now = new Date()
  const defaultMonth = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`
  const selectedMonth = month ?? defaultMonth

  const monthOptions = Array.from({ length: 6 }, (_, i) => {
    const d = new Date(now.getFullYear(), now.getMonth() - i, 1)
    return {
      value: `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`,
      label: d.toLocaleDateString('id-ID', { month: 'long', year: 'numeric' }),
    }
  })

  // Auto-generate draft untuk tutor yang belum punya slip di bulan ini
  await autoGenerateDraftPayslips(selectedMonth)

  const admin = createAdminClient()

  let query = admin
    .from('payslips')
    .select('*')
    .eq('month', selectedMonth)
    .eq('is_deleted', false)
    .order('created_at', { ascending: false })

  if (status) query = query.eq('status', status)

  const { data: payslips } = await query as unknown as { data: PayslipRow[] | null }
  const list = payslips ?? []

  const totalGrand = list.reduce((s, p) => s + p.grand_total, 0)
  const totalPaid = list.filter(p => p.status === 'paid').reduce((s, p) => s + p.grand_total, 0)
  const totalPending = list.filter(p => p.status !== 'paid').reduce((s, p) => s + p.grand_total, 0)

  const [year, mon] = selectedMonth.split('-').map(Number)
  const payDate = new Date(year, mon, 1).toLocaleDateString('id-ID', { day: 'numeric', month: 'long', year: 'numeric' })
  const workMonthLabel = new Date(year, mon - 1, 1).toLocaleDateString('id-ID', { month: 'long', year: 'numeric' })

  return (
    <div>
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-xl font-semibold text-gray-900">Slip Gaji Tutor</h1>
          <p className="text-sm text-gray-500 mt-1">
            Gaji bulan <strong>{workMonthLabel}</strong> dibayarkan pada <strong>{payDate}</strong>
          </p>
        </div>
        <Link
          href={`/admin/payslips/generate?month=${selectedMonth}`}
          className="inline-flex items-center gap-2 bg-blue-600 text-white text-sm font-medium px-4 py-2 rounded-lg hover:bg-blue-700 transition-colors"
        >
          <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
          </svg>
          Buat Slip Gaji
        </Link>
      </div>

      <div className="mb-5">
        <MonthSelect options={monthOptions} value={selectedMonth} />
      </div>

      {/* Summary */}
      <div className="grid grid-cols-3 gap-4 mb-6">
        <div className="bg-blue-50 rounded-xl p-4">
          <p className="text-xs font-medium text-blue-600">Total Gaji</p>
          <p className="text-xl font-bold text-blue-700 mt-1">{formatRupiah(totalGrand)}</p>
          <p className="text-xs text-blue-500 mt-0.5">{list.length} tutor</p>
        </div>
        <div className="bg-green-50 rounded-xl p-4">
          <p className="text-xs font-medium text-green-600">Sudah Dibayar</p>
          <p className="text-xl font-bold text-green-700 mt-1">{formatRupiah(totalPaid)}</p>
          <p className="text-xs text-green-500 mt-0.5">{list.filter(p => p.status === 'paid').length} slip</p>
        </div>
        <div className="bg-amber-50 rounded-xl p-4">
          <p className="text-xs font-medium text-amber-600">Belum Dibayar</p>
          <p className="text-xl font-bold text-amber-700 mt-1">{formatRupiah(totalPending)}</p>
          <p className="text-xs text-amber-500 mt-0.5">{list.filter(p => p.status !== 'paid').length} slip</p>
        </div>
      </div>

      {/* Status filter tabs */}
      <div className="flex gap-2 mb-4">
        {[
          { key: '', label: 'Semua' },
          { key: 'draft', label: 'Draft' },
          { key: 'sent', label: 'Terkirim' },
          { key: 'paid', label: 'Dibayar' },
        ].map(tab => (
          <Link
            key={tab.key}
            href={`/admin/payslips?month=${selectedMonth}${tab.key ? `&status=${tab.key}` : ''}`}
            className={`px-3 py-1.5 text-sm rounded-full font-medium transition-colors ${
              (status ?? '') === tab.key
                ? 'bg-blue-600 text-white'
                : 'bg-white border border-gray-200 text-gray-600 hover:bg-gray-50'
            }`}
          >
            {tab.label}
          </Link>
        ))}
      </div>

      {list.length === 0 ? (
        <div className="bg-white rounded-xl shadow ring-1 ring-gray-900/5 p-12 text-center">
          <p className="text-sm text-gray-500 mb-3">Belum ada slip gaji untuk bulan ini.</p>
          <Link
            href={`/admin/payslips/generate?month=${selectedMonth}`}
            className="text-sm text-blue-600 hover:underline font-medium"
          >
            Buat slip gaji sekarang →
          </Link>
        </div>
      ) : (
        <div className="bg-white rounded-xl shadow ring-1 ring-gray-900/5 overflow-hidden">
          <table className="w-full text-sm">
            <thead className="bg-gray-50 border-b border-gray-100">
              <tr>
                <th className="text-left px-5 py-3 text-xs font-semibold text-gray-500">No. Slip</th>
                <th className="text-left px-5 py-3 text-xs font-semibold text-gray-500">Tutor</th>
                <th className="text-center px-4 py-3 text-xs font-semibold text-gray-500">Sesi</th>
                <th className="text-right px-4 py-3 text-xs font-semibold text-gray-500">Total Gaji</th>
                <th className="text-center px-4 py-3 text-xs font-semibold text-gray-500">Status</th>
                <th className="text-right px-5 py-3 text-xs font-semibold text-gray-500">Aksi</th>
              </tr>
            </thead>
            <tbody className="divide-y">
              {list.map(p => (
                <tr key={p.id} className="hover:bg-gray-50">
                  <td className="px-5 py-3 font-mono text-xs text-gray-500">{p.payslip_number}</td>
                  <td className="px-5 py-3 font-medium text-gray-900">{p.tutor_name}</td>
                  <td className="px-4 py-3 text-center text-gray-600">{p.total_sessions}</td>
                  <td className="px-4 py-3 text-right font-semibold text-gray-900">{formatRupiah(p.grand_total)}</td>
                  <td className="px-4 py-3 text-center">
                    <span className={`text-xs font-medium px-2 py-1 rounded-full ${STATUS_COLOR[p.status]}`}>
                      {STATUS_LABEL[p.status]}
                    </span>
                  </td>
                  <td className="px-5 py-3 text-right">
                    <Link
                      href={`/admin/payslips/${p.id}`}
                      className="text-xs text-blue-600 hover:underline font-medium"
                    >
                      Detail →
                    </Link>
                  </td>
                </tr>
              ))}
            </tbody>
            <tfoot className="border-t bg-gray-50">
              <tr>
                <td className="px-5 py-3 text-xs font-semibold text-gray-600" colSpan={3}>Total</td>
                <td className="px-4 py-3 text-right text-xs font-semibold text-gray-900">{formatRupiah(totalGrand)}</td>
                <td colSpan={2} />
              </tr>
            </tfoot>
          </table>
        </div>
      )}
    </div>
  )
}
