import { createAdminClient } from '@/lib/supabase/server-admin'
import Link from 'next/link'
import MetricCard from '@/components/dashboard/MetricCard'
import GenerateDraftButton from '@/components/admin/GenerateDraftButton'
import PayslipFilters from '@/components/admin/payslips/PayslipFilters'
import { autoGenerateDraftPayslips } from '@/lib/actions/admin/payslips'
import type { PayslipRow } from '@/lib/types/database'

function formatRupiah(n: number) {
  return new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(n)
}

const STATUS_LABEL: Record<string, string> = {
  draft: 'Draft',
  sent: 'Terkirim',
  paid: 'Dibayar',
}
const STATUS_COLOR: Record<string, string> = {
  draft: 'bg-gray-100 text-gray-500',
  sent:  'bg-blue-100 text-blue-700',
  paid:  'bg-green-100 text-green-700',
}

const MONTH_LABELS = ['Jan', 'Feb', 'Mar', 'Apr', 'Mei', 'Jun', 'Jul', 'Agu', 'Sep', 'Okt', 'Nov', 'Des']

export default async function PayslipsPage({
  searchParams,
}: {
  searchParams: Promise<{ month?: string; status?: string; q?: string }>
}) {
  const { month = '', status = '', q = '' } = await searchParams
  const now = new Date()
  const currentYear = now.getFullYear()
  const currentMonth = `${currentYear}-${String(now.getMonth() + 1).padStart(2, '0')}`
  const activeMonth = month || currentMonth

  const [year, mon] = activeMonth.split('-').map(Number)
  const workMonthLabel = new Date(year, mon - 1, 1).toLocaleDateString('id-ID', { month: 'long', year: 'numeric' })
  const payDate = new Date(year, mon, 1).toLocaleDateString('id-ID', { day: 'numeric', month: 'long', year: 'numeric' })

  const monthTabs = MONTH_LABELS.map((label, i) => ({
    label,
    value: `${currentYear}-${String(i + 1).padStart(2, '0')}`,
  }))

  const admin = createAdminClient()

  let query = admin
    .from('payslips')
    .select('*')
    .eq('month', activeMonth)
    .eq('is_deleted', false)
    .order('tutor_name', { ascending: true })

  if (status) query = query.eq('status', status)

  const { data: payslips } = await query as unknown as { data: PayslipRow[] | null }
  const allFiltered = payslips ?? []
  const list = q
    ? allFiltered.filter(p => p.tutor_name.toLowerCase().includes(q.toLowerCase()))
    : allFiltered

  // Stats for the active month (unfiltered by status)
  const { data: allForMonth } = await admin
    .from('payslips')
    .select('grand_total, status')
    .eq('month', activeMonth)
    .eq('is_deleted', false) as unknown as { data: { grand_total: number; status: string }[] | null }

  const allList = allForMonth ?? []
  const totalGrand   = allList.reduce((s, p) => s + p.grand_total, 0)
  const totalPaid    = allList.filter(p => p.status === 'paid').reduce((s, p) => s + p.grand_total, 0)
  const totalPending = allList.filter(p => p.status !== 'paid').reduce((s, p) => s + p.grand_total, 0)
  const paidCount    = allList.filter(p => p.status === 'paid').length
  const unpaidCount  = allList.filter(p => p.status !== 'paid').length

  function tabUrl(newMonth: string) {
    const p = new URLSearchParams()
    if (newMonth) p.set('month', newMonth)
    p.delete('status')
    return `/admin/payslips?${p.toString()}`
  }

  return (
    <div className="space-y-5">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-xl font-semibold text-gray-900">Slip Gaji Tutor</h1>
          <p className="text-sm text-gray-500 mt-0.5">
            Gaji bulan <strong>{workMonthLabel}</strong> dibayarkan pada <strong>{payDate}</strong>
          </p>
        </div>
      </div>

      {/* Summary */}
      <div className="grid grid-cols-3 gap-3">
        <MetricCard
          label="Total Gaji"
          value={formatRupiah(totalGrand)}
          sub={`${allList.length} tutor`}
        />
        <MetricCard
          label="Sudah Dibayar"
          value={formatRupiah(totalPaid)}
          sub={paidCount > 0 ? `${paidCount} slip lunas` : undefined}
        />
        <MetricCard
          label="Belum Dibayar"
          value={formatRupiah(totalPending)}
          sub={unpaidCount > 0 ? `${unpaidCount} slip pending` : undefined}
        />
      </div>

      {/* Monthly tabs */}
      <div className="bg-white border border-slate-200 rounded-2xl overflow-hidden">
        <div className="flex overflow-x-auto">
          {monthTabs.map(tab => (
            <Link
              key={tab.value}
              href={tabUrl(tab.value)}
              className={`flex-none px-4 py-3 text-sm font-medium border-b-2 transition-colors whitespace-nowrap ${
                activeMonth === tab.value
                  ? 'border-blue-600 text-blue-600 bg-blue-50/50'
                  : 'border-transparent text-gray-500 hover:text-gray-700 hover:bg-slate-50'
              }`}
            >
              {tab.label}
            </Link>
          ))}
        </div>
      </div>

      {/* Search + Status filter */}
      <PayslipFilters q={q} statusFilter={status} month={activeMonth} />

      {/* Table */}
      <div className="bg-white border border-slate-200 rounded-2xl overflow-hidden">
        <div className="px-5 pt-5 pb-3 flex items-center justify-between">
          <h2 className="text-xs font-semibold text-gray-500 uppercase tracking-widest">
            {(q || status)
              ? `Menampilkan ${list.length} dari ${allList.length} slip gaji`
              : `${allList.length} Slip Gaji`}
          </h2>
          {activeMonth === currentMonth && (
            <GenerateDraftButton
              month={activeMonth}
              monthLabel={workMonthLabel}
              action={autoGenerateDraftPayslips}
            />
          )}
        </div>

        {list.length === 0 ? (
          <p className="text-sm text-gray-500 text-center py-10 px-5">
            Belum ada slip gaji untuk bulan ini.
          </p>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-t border-slate-100 bg-slate-50 text-xs font-semibold text-gray-500 uppercase tracking-wide">
                  <th className="pl-5 pr-4 py-3 text-left">Tutor</th>
                  <th className="px-4 py-3 text-left hidden sm:table-cell">No. Slip</th>
                  <th className="px-4 py-3 text-center hidden md:table-cell">Sesi</th>
                  <th className="px-4 py-3 text-right">Total Gaji</th>
                  <th className="px-4 py-3 text-left">Status</th>
                  <th className="px-4 py-3" />
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {list.map(p => (
                  <tr key={p.id} className="hover:bg-slate-50 transition-colors cursor-pointer">
                    <td className="pl-5 pr-4 py-3">
                      <Link href={`/admin/payslips/${p.id}`} className="block font-medium text-gray-900">
                        {p.tutor_name}
                      </Link>
                    </td>
                    <td className="px-4 py-3 hidden sm:table-cell">
                      <Link href={`/admin/payslips/${p.id}`} className="block font-mono text-gray-500">
                        {p.payslip_number}
                      </Link>
                    </td>
                    <td className="px-4 py-3 text-center hidden md:table-cell">
                      <Link href={`/admin/payslips/${p.id}`} className="block text-gray-600">
                        {p.total_sessions}
                      </Link>
                    </td>
                    <td className="px-4 py-3 text-right">
                      <Link href={`/admin/payslips/${p.id}`} className="block font-semibold text-gray-900">
                        {formatRupiah(p.grand_total)}
                      </Link>
                    </td>
                    <td className="px-4 py-3">
                      <Link href={`/admin/payslips/${p.id}`} className="block">
                        <span className={`inline-flex text-sm font-medium px-2 py-0.5 rounded-full ${STATUS_COLOR[p.status] ?? 'bg-gray-100 text-gray-500'}`}>
                          {STATUS_LABEL[p.status] ?? p.status}
                        </span>
                      </Link>
                    </td>
                    <td className="px-4 py-3 text-right">
                      <Link href={`/admin/payslips/${p.id}`} className="inline-block">
                        <svg className="w-4 h-4 text-gray-300" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
                        </svg>
                      </Link>
                    </td>
                  </tr>
                ))}
              </tbody>
              <tfoot className="border-t border-slate-100 bg-slate-50">
                <tr>
                  <td className="pl-5 pr-4 py-3 text-sm font-semibold text-gray-600" colSpan={3}>Total</td>
                  <td className="px-4 py-3 text-right text-sm font-semibold text-gray-900">{formatRupiah(totalGrand)}</td>
                  <td colSpan={2} />
                </tr>
              </tfoot>
            </table>
          </div>
        )}
      </div>
    </div>
  )
}
