-- Seed curriculum topics Matematika SD Kelas 1-6
-- Sumber: CP_Per_Kelas_1.xlsx
-- Kolom Elemen dari Excel → kolom theme (tema) di database
-- Kolom Nomor → kolom topic di database
-- Kolom Deskripsi → kolom learning_outcomes di database

do $$
declare
  math_subject_id uuid;
begin
  -- Insert subject Matematika SD jika belum ada
  insert into subjects (name, description, level)
  values ('Matematika', 'Matematika Sekolah Dasar', array['SD'])
  on conflict do nothing;

  select id into math_subject_id
  from subjects
  where name = 'Matematika' and 'SD' = any(level)
  limit 1;

  if math_subject_id is null then
    raise exception 'Subject Matematika SD tidak ditemukan setelah insert';
  end if;

  -- Hapus data lama untuk kelas 1-6 jika ada
  delete from curriculum_topics
  where subject_id = math_subject_id
    and grade_level in ('Kelas 1','Kelas 2','Kelas 3','Kelas 4','Kelas 5','Kelas 6');

  -- Insert 188 capaian pembelajaran
  insert into curriculum_topics (subject_id, grade_level, semester, theme, topic, learning_outcomes, sort_order)
  values
  (math_subject_id, 'Kelas 1', 1, 'Bilangan', '1.1.1', 'Mengenal bilngan dan simbol bilangan 1-10 berdasarkan kumpulan benda', 0),
  (math_subject_id, 'Kelas 1', 1, 'Bilangan', '1.1.2', 'Membaca dan menuliskan bilangan cacah sampai dengan10', 1),
  (math_subject_id, 'Kelas 1', 1, 'Bilangan', '1.1.3', 'Menghitung maju dan mundur bilngan 1-10', 2),
  (math_subject_id, 'Kelas 1', 1, 'Bilangan', '1.1.4', 'Menyusun bilangan dengan menggunakan model konkret', 3),
  (math_subject_id, 'Kelas 1', 1, 'Bilangan', '1.1.5', 'Mengenal bilangan dan simbol bilangan cacah 11-20', 4),
  (math_subject_id, 'Kelas 1', 1, 'Bilangan', '1.1.6', 'Membaca dan menuliskan bilagan cacah sampai 20', 5),
  (math_subject_id, 'Kelas 1', 1, 'Bilangan', '1.1.7', 'Mengientifikasi jumlah bilangan yang lebih banyak, sama atau lebih sedikit dengan menggunakan benda konkret dan simbol', 6),
  (math_subject_id, 'Kelas 1', 1, 'Bilangan', '1.1.8', 'Membandingkan dan mengurutkan bilangan cacah dengan urutan naik { kecil ke besar } atua sebaliknya', 7),
  (math_subject_id, 'Kelas 1', 1, 'Bilangan', '1.1.9', 'Meletakan beberapa bilangan cacah pada garis bilangan', 8),
  (math_subject_id, 'Kelas 1', 1, 'Bilangan', '1.1.10', 'Mengenal nilai tempat suatu bilangan { konsep satuan dan puluhan menggunakan kumpulan benda', 9),
  (math_subject_id, 'Kelas 1', 1, 'Bilangan', '1.1.11', 'Membedakan dua bilangan berdasarkan nilai tempat { nilai tempat menunjukan jumlah atau nilia suatu bilangan', 10),
  (math_subject_id, 'Kelas 1', 1, 'Bilangan', '1.1.12', 'Menunjukan konsep penjumlahan sampai dengan 20 dengan benda konkret, gambar, cerita, atau cara manipulatif lainnya', 11),
  (math_subject_id, 'Kelas 1', 1, 'Bilangan', '1.1.13', 'Menjumlahkan menggunakan dua bilangan cacah sampai 20', 12),
  (math_subject_id, 'Kelas 1', 1, 'Bilangan', '1.1.14', 'Menunjukan konsep penurangan sampai dengan 20 dengan benda konkret, gambar, cerita, atau cara manipulatif lainnya.', 13),
  (math_subject_id, 'Kelas 1', 1, 'Bilangan', '1.1.15', 'Pengurangan menggunakan dua bilangan cacah sampai dengan 20', 14),
  (math_subject_id, 'Kelas 1', 1, 'Aljabar', '1.2.1', 'Menggunakan gambar, obyek, bilangan dan suara dalam bentuk pola. { terkait suara dalam bentuk pola, dapat dilakukan dengan tepuk }', 15),
  (math_subject_id, 'Kelas 1', 1, 'Aljabar', '1.2.2', 'Membuat pola bilangan yang berkaitan dengan kumpulan benda-benda, obyek, dan bilangan', 16),
  (math_subject_id, 'Kelas 1', 1, 'Pengukuran', '1.3.1', 'Membandingkan 2 obyek benda { lebih panjang dan lebih pendek }', 17),
  (math_subject_id, 'Kelas 1', 1, 'Pengukuran', '1.3.2', 'Mengurutkan benda berdasarkan panjang dan berat. { lebih panjang dan lebih pendek , lebih tinggi dan lebih rendah, lebiih berat dan lebih ringan }', 18),
  (math_subject_id, 'Kelas 1', 1, 'Pengukuran', '1.3.3', 'Mengenal dan menentukan panjang dan berat suatu benda dengan menggunakan satuan tidak baku', 19),
  (math_subject_id, 'Kelas 1', 1, 'Pengukuran', '1.3.4', 'Mengenal satuan waktu jam. { cara membaca dan menunjukan jam tanpa menit dan detik, misal jam 5 }', 20),
  (math_subject_id, 'Kelas 1', 1, 'Pengukuran', '1.3.5', 'Membuat perkiraan waktu. { Misal "lama"atau"sebentar" dalam kehidupan sehari hari }', 21),
  (math_subject_id, 'Kelas 1', 1, 'Geometri', '1.4.1', 'Mengenal bangun dua dimensi menggunakan benda konkret { segitiga, segiempat, segibanyak, lingkaran }', 22),
  (math_subject_id, 'Kelas 1', 1, 'Geometri', '1.4.2', 'Mengenal ciri-ciri bangun dua dimensi { segitiga, segiempat, segibanyak, dan lingkaran }', 23),
  (math_subject_id, 'Kelas 1', 1, 'Geometri', '1.4.3', 'Mengelompokan bangun dua dimensi tertentu { segitiga, segiempat, segibanyak, dan lingkaran }', 24),
  (math_subject_id, 'Kelas 1', 1, 'Geometri', '1.4.4', 'Menggambar bentuk bangun dua dimensi { segitiga, segiempat, segibanyak,lingkaran }', 25),
  (math_subject_id, 'Kelas 1', 1, 'Analisis Data', '1.5.1', 'Membilang dan mengurutkan benda-benda berdasarkan atribut', 26),
  (math_subject_id, 'Kelas 1', 1, 'Analisis Data', '1.5.2', 'Membandingkan benda-benda berdasarkan atribut', 27),
  (math_subject_id, 'Kelas 1', 1, 'Analisis Data', '1.5.3', 'Membuat pertayaan sederhanan untuk mengumpulkan data', 28),
  (math_subject_id, 'Kelas 1', 1, 'Analisis Data', '1.5.4', 'Mengumpulkan data dengan bertanya pada rekan dan guru', 29),
  (math_subject_id, 'Kelas 1', 1, 'Analisis Data', '1.5.5', 'Membuat grafik dengan menggunakan benda atau menempel gambar', 30),
  (math_subject_id, 'Kelas 2', 1, 'Bilangan', '2.1.1', 'Mengenal bilangan dan simbol bilangan cacah 21-20', 0),
  (math_subject_id, 'Kelas 2', 1, 'Bilangan', '2.1.2', 'Mengenal bilangan dan simbol bilangan 51-100', 1),
  (math_subject_id, 'Kelas 2', 1, 'Bilangan', '2.1.3', 'Membandingkan dan mengurutkan bilangan cacah sampai angka 100', 2),
  (math_subject_id, 'Kelas 2', 1, 'Bilangan', '2.1.4', 'Membandingkan dan mengurutkan  bilangan dan simbol  bilangan cacah sampai angka 100', 3),
  (math_subject_id, 'Kelas 2', 1, 'Bilangan', '2.1.5', 'Meletakkan garis bilangan dan posisi bilangan cacah pada garis bilangan sampai angka 100 { misal menggunanakan angka 81- 90 dan sebagainya }', 4),
  (math_subject_id, 'Kelas 2', 1, 'Bilangan', '2.1.6', 'Mengidentifikasi jumlah bilangan yang lebih banyak, sama atau lebih sedikit dengan menggunakan simbol  bilangan 100', 5),
  (math_subject_id, 'Kelas 2', 1, 'Bilangan', '2.1.7', 'Mengenal nilai tempat suatu bilangan { konsep satuan, puluhan dan ratusan menggunakan kumpulan benda', 6),
  (math_subject_id, 'Kelas 2', 1, 'Bilangan', '2.1.8', 'Memahami nilai tempat menunjukan jumlah sesuatu bilangan. Misal : 385, 538 dan 853 adalah bilangan berbeda', 7),
  (math_subject_id, 'Kelas 2', 1, 'Bilangan', '2.1.9', 'Membedakan nilai tempat bilangan cacah sampai dengan 100 dengan mengengelompokan menjadi ratusan, puluhan, dan satuan', 8),
  (math_subject_id, 'Kelas 2', 1, 'Bilangan', '2.1.10', 'Melaksanakan penjumlahan dan pengurangan dua bilangan cacah dangan teknik menyimpan atau meminjam', 9),
  (math_subject_id, 'Kelas 2', 1, 'Bilangan', '2.1.11', 'Memahami hubungan antara operasional bilangan.{ hubungan penjumlahan dengan perkalian, yakni perkalian adalah pejumlahan berulang, hubungan pengurangan dengan pembagian, yakni pepmbagian adalah pengurangan berulang', 10),
  (math_subject_id, 'Kelas 2', 1, 'Bilangan', '2.1.12', 'Mengenal konsep kelipatan dan faktor sederhana', 11),
  (math_subject_id, 'Kelas 2', 1, 'Bilangan', '2.1.13', 'Melaksanakan perkalian dan pembagian dua bilangan cacah sampai dengan 10', 12),
  (math_subject_id, 'Kelas 2', 1, 'Bilangan', '2.1.14', 'Mendeskripsikan bilangan pecahan sebagai bagian dari pembagian dua bilangan cacah sampai dengan 10', 13),
  (math_subject_id, 'Kelas 2', 1, 'Bilangan', '2.1.14', 'Mendeskripsikan bilangan pecahan sebagai bagian dari bilangan cacah yang utuh', 14),
  (math_subject_id, 'Kelas 2', 1, 'Bilangan', '2.1.15', 'Menunjukan makna 1/2, 1/4, dan 1/8 dengan menggunakan benda konkret. Misal kue, pudding atau sebagainya', 15),
  (math_subject_id, 'Kelas 2', 1, 'Bilangan', '2.1.16', 'Menunjukan makna 1/2, 1/4, dan 1/8 dengan menggunakan sekumpulan objek', 16),
  (math_subject_id, 'Kelas 2', 1, 'Bilangan', '2.1.17', 'Menunjukan makna bagian 1/2, 1/4, dan 1/8 melalui sebuah gambar.', 17),
  (math_subject_id, 'Kelas 2', 1, 'Bilangan', '2.1.18', 'Membandingkan dan mengurutkan pecahan menggunakan sekumpulan objek', 18),
  (math_subject_id, 'Kelas 2', 1, 'Aljabar', '2.2.1', 'Memprediksi pola bilangan yang berkaitan dengan kumpulan benda-benda, obyek, bilangan dan bilangan.', 19),
  (math_subject_id, 'Kelas 2', 1, 'Aljabar', '2.2.2', 'Menemukan pola gambar atau obyek sederhana', 20),
  (math_subject_id, 'Kelas 2', 1, 'Aljabar', '2.2.3', 'Mengidentifikasi pola dalam urutan bilangan { ganjil dan genap }', 21),
  (math_subject_id, 'Kelas 2', 1, 'Pengukuran', '2.3.1', 'Melakukan dan menunjukan panjang suatu benda dengan menggunakan satuan pengukuran standard. { Misal : panjang 1 cm }', 22),
  (math_subject_id, 'Kelas 2', 1, 'Pengukuran', '2.3.2', 'Melakukan dan menunjukan berat suatu benda dengan menggunakan satuan pengukuran standar { timbangan }. { Misal : gram atau kilogram }', 23),
  (math_subject_id, 'Kelas 2', 1, 'Pengukuran', '2.3.3', 'Memahami cara membaca dan menunjukan jam dan menit. { Misal jam 6 lebih 15 menit }', 24),
  (math_subject_id, 'Kelas 2', 1, 'Pengukuran', '2.3.4', 'Membandingkan suatu benda dengan satuan baku panjang { cm,m }, berat { gr,kg }, volume { liter,ml } dan waktu { menit, detik }', 25),
  (math_subject_id, 'Kelas 2', 1, 'Geometri', '2.4.1', 'Menggabungkan beberapa bangun dua dimensi membentuk bangun dua dimensi gabungan.', 26),
  (math_subject_id, 'Kelas 2', 1, 'Geometri', '2.4.2', 'Mengenal bangun tiga dimensi menggunakan benda konkret { balok dan kubus }', 27),
  (math_subject_id, 'Kelas 2', 1, 'Geometri', '2.4.3', 'Mengklasifikasi bangun tiga dimensi berdsarkan ciri-cirinya { balok, dan kubus }', 28),
  (math_subject_id, 'Kelas 2', 1, 'Geometri', '2.4.4', 'Membangun sebuah bentuk atau bangunan dengan menggunakan balok dan kubus .', 29),
  (math_subject_id, 'Kelas 2', 1, 'Geometri', '2.4.5', 'Mendeskripsikan persamaan dan perbedaan antara balok dan kubus', 30),
  (math_subject_id, 'Kelas 2', 1, 'Geometri', '2.4.6', 'Menggambar dua dimensi balok dan kubus', 31),
  (math_subject_id, 'Kelas 2', 1, 'Analisis Data', '2.5.1', 'Mengumpulkan data dengan bertanya pada rekan dan guru', 32),
  (math_subject_id, 'Kelas 2', 1, 'Analisis Data', '2.5.2', 'Menyajikan banyak benda dalam bentuk turus', 33),
  (math_subject_id, 'Kelas 2', 1, 'Analisis Data', '2.5.3', 'Menyajikan banyaknya benda dengan menggunkan gambar', 34),
  (math_subject_id, 'Kelas 2', 1, 'Analisis Data', '2.5.4', 'Mengurutkan dan membandingkan data dengan menggunakan turus dan gambar', 35),
  (math_subject_id, 'Kelas 3', 1, 'Bilangan', '3.1.1', 'Mengidentifikasian pola aritmeitk { termasuk pola pada tabel penjumlahan dan perkalian } dan menjelaskannya menggunakan sifat dari operasi hitung', 0),
  (math_subject_id, 'Kelas 3', 1, 'Bilangan', '3.1.2', 'Mengidentifikasikan jumlah dari susunan grup struktur, perkalian dan nilaia tempat', 1),
  (math_subject_id, 'Kelas 3', 1, 'Bilangan', '3.1.3', 'Penjumlahan dan pengurangan hingga 1000 dengan fasih menggunakan berbagai strategi operasi hitung berdasarkan nilai tempat, sifat operasi hitung dan hubungan antara penjumlahan dan pengurangan', 2),
  (math_subject_id, 'Kelas 3', 1, 'Bilangan', '3.1.4', 'Menafsirkan perkalian dan pembagian dengan membuat grup dengan jumlah obyek yang sama', 3),
  (math_subject_id, 'Kelas 3', 1, 'Bilangan', '3.1.5', 'Menghubungkan perkalian dan pembagian pada model grup yang sama pada setiap grup, himpunan dan luas persegi panjang', 4),
  (math_subject_id, 'Kelas 3', 1, 'Bilangan', '3.1.6', 'Menunjukan pembagian sebagai faktor bilangan yang belum diketahui', 5),
  (math_subject_id, 'Kelas 3', 1, 'Bilangan', '3.1.7', 'Mengaplikasikan sifat opersi hitung sebagai strategi untuk perkalian dan pembagian', 6),
  (math_subject_id, 'Kelas 3', 1, 'Bilangan', '3.1.8', 'Perkalian bilangan bulat 10 atau 100', 7),
  (math_subject_id, 'Kelas 3', 1, 'Bilangan', '3.1.9', 'Menggunakan nilai tempat untuk memahami pembulatan bilangan bulat hingga 10 atau 100', 8),
  (math_subject_id, 'Kelas 3', 1, 'Bilangan', '3.1.10', 'Menunjukan bahwa sebuah pecahan adalah 1/b pada garis bilangan, dan pecahan a/b pada garis bilangan', 9),
  (math_subject_id, 'Kelas 3', 1, 'Bilangan', '3.1.11', 'Menjelaskan pecahan setara memiliki ukuran yang sama atau pada titik yang sama pada garis bilangan { termasuk menunjukan bahwa pecahan adlah bilangan bulat.', 10),
  (math_subject_id, 'Kelas 3', 1, 'Bilangan', '3.1.12', 'Menghasilkan pecahan setara dengan mengalikan atau membagi penyebut dan pembilang dengan faktor yang sama', 11),
  (math_subject_id, 'Kelas 3', 1, 'Bilangan', '3.1.13', 'Membandingkan pecahan tidak setara dengan keseluruhan yang sama menggunakan pecahan setara', 12),
  (math_subject_id, 'Kelas 3', 1, 'Bilangan', '3.1.14', 'Penjumlahan dan pengurangan dua pecahan yang terkait { termasuk pecahan perseratus } dalam satu kesatuan dengan penyebut yang sama', 13),
  (math_subject_id, 'Kelas 3', 1, 'Bilangan', '3.1.15', 'Penjumlahan dan pengurangan pecahan dengan penyebut yang sama', 14),
  (math_subject_id, 'Kelas 3', 1, 'Bilangan', '3.1.16', 'Perkalian dan pembagian dengan fasih hingga 100', 15),
  (math_subject_id, 'Kelas 3', 1, 'Pengukuran', '3.2.1', 'Memperkirakan panjang dengan unit tidak baku { con : jengkal, stik eskrim, klip kertas dsb }', 16),
  (math_subject_id, 'Kelas 3', 1, 'Pengukuran', '3.2.2', 'Mengukur  panjang dengan unit ukur { co cm, m }', 17),
  (math_subject_id, 'Kelas 3', 1, 'Pengukuran', '3.2.3', 'Menghitung luas persegi panjang dari sisi panjang dan lebar dan menjelaskan bagaimana perkalian dapat mengkur sebuah luas bidang', 18),
  (math_subject_id, 'Kelas 3', 1, 'Pengukuran', '3.2.4', 'Menghubungkan satuan unit untuk mengukur luas', 19),
  (math_subject_id, 'Kelas 3', 1, 'Pengukuran', '3.2.5', 'Menggunakan gambar untuk menunjukan ciri-ciri distribusi', 20),
  (math_subject_id, 'Kelas 3', 1, 'Pengukuran', '3.2.6', 'Menggunakan kubus untuk mengisi sebuah bangunan dan manggunakan lapisan atau ide perkalian { kelipatan }', 21),
  (math_subject_id, 'Kelas 3', 1, 'Pengukuran', '3.2.7', 'Menjelaskan bahwa menghitung isi atau volume terdiri dari unit kecil dan sebaliknya.', 22),
  (math_subject_id, 'Kelas 3', 1, 'Geometri', '3.3.1', 'Mengidentifikasi bahwa sudut terbentuk dari 2 garis yang bertemu pada satu titik yang sama', 23),
  (math_subject_id, 'Kelas 3', 1, 'Geometri', '3.3.2', 'Mengidentifikasi  bahwa sudut diukur dari rotasi garis yang satu ke garis yang lain', 24),
  (math_subject_id, 'Kelas 3', 1, 'Geometri', '3.3.3', 'Mengidentifikasi sudut lancip dan tumpul', 25),
  (math_subject_id, 'Kelas 3', 1, 'Geometri', '3.3.4', 'Membandingkan bangun datar berdasarkan ciri-cirinya', 26),
  (math_subject_id, 'Kelas 3', 1, 'Geometri', '3.3.5', 'Mengelompokkan bangun data berdasarkan ciri-cirinya termasuk sudut', 27),
  (math_subject_id, 'Kelas 3', 1, 'Geometri', '3.3.6', 'Memahami bahwa bangun datar dapat memilliki ciri tersebut dapat dikelompokkan ke kategori yang lebih luas { con : persegi, ppersegi panjang, dan belah ketupat memiliki 4 sisi,  dan bangun datar ini dapat dikategorikan sebagai segi empat }', 28),
  (math_subject_id, 'Kelas 3', 1, 'Geometri', '3.3.7', 'Menggunakan berbagai bentuk untuk prengubinan', 29),
  (math_subject_id, 'Kelas 3', 1, 'Geometri', '3.3.8', 'Mengenali bangun datar pembentuk suatu bangun dalan pengubinan', 30),
  (math_subject_id, 'Kelas 3', 1, 'Analisi Data dan Peluang', '3.4.1', 'Mengumpulkan data dengan observasi, survei dan percobaan', 31),
  (math_subject_id, 'Kelas 3', 1, 'Analisi Data dan Peluang', '3.4.2', 'Membuat dan menganalisis tabel frekuensi, diagram batang, piktogram, diagram garis dan menggunakannya untuk menyelesaikan masalah', 32),
  (math_subject_id, 'Kelas 3', 1, 'Analisi Data dan Peluang', '3.4.3', 'Menjelaskan data pada diagram dan membandinhkan diagram serupa', 33),
  (math_subject_id, 'Kelas 3', 1, 'Analisi Data dan Peluang', '3.4.4', 'Melakukan percobaaan sederhana berkaitan dengan peluang Memperkirakan hasil dari percobaan sederhana', 34),
  (math_subject_id, 'Kelas 4', 1, 'Bilangan', '4.1.1', 'Menghasilkan pola angka atau bentuk dengan aturan pola tertentu', 0),
  (math_subject_id, 'Kelas 4', 1, 'Bilangan', '4.1.2', 'Mengidentifikasi ciri-ciri yang terlihat pada sebuah pola yang tak tampak pada pola tersebut', 1),
  (math_subject_id, 'Kelas 4', 1, 'Bilangan', '4.1.3', 'Membandingkan perkalian dan pembagian', 2),
  (math_subject_id, 'Kelas 4', 1, 'Bilangan', '4.1.4', 'Mencari faktor pengali dan pembagi dari bilangan bulat', 3),
  (math_subject_id, 'Kelas 4', 1, 'Bilangan', '4.1.5', 'mengidentifikasi bilangan prima dan komposit', 4),
  (math_subject_id, 'Kelas 4', 1, 'Bilangan', '4.1.6', 'Mencari faktor prima dari bilangan bulat', 5),
  (math_subject_id, 'Kelas 4', 1, 'Bilangan', '4.1.7', 'Perkalian dengan menggunakan berbagai strategi', 6),
  (math_subject_id, 'Kelas 4', 1, 'Bilangan', '4.1.8', 'Pembagian dengan berbagai strategi', 7),
  (math_subject_id, 'Kelas 4', 1, 'Bilangan', '4.1.9', 'Mengenali bahwa sebuah angka pada nilai tempat tertentu adalah 10 kali dan nilai tempat pada angka di kanannya', 8),
  (math_subject_id, 'Kelas 4', 1, 'Bilangan', '4.1.10', 'Membaca dan menulis bilangan bulat menggunakan perpuluhan, penyebutan angka dan dalam bentuk terurai { con : 521 = 5  ratus + 1 satuan }', 9),
  (math_subject_id, 'Kelas 4', 1, 'Bilangan', '4.1.11', 'Membandingkan 2 angka puluhan atau ratusan', 10),
  (math_subject_id, 'Kelas 4', 1, 'Bilangan', '4.1.12', 'Pembulatan bilangan cacah', 11),
  (math_subject_id, 'Kelas 4', 1, 'Bilangan', '4.1.13', 'Memahami hubungan antara pecahan biasa dan pecahan campuran', 12),
  (math_subject_id, 'Kelas 4', 1, 'Bilangan', '4.1.14', 'Penjumlahan dan pengurangan pecahan biasa dan campuran dengan penyebut yang sama atau berbeda', 13),
  (math_subject_id, 'Kelas 4', 1, 'Bilangan', '4.1.15', 'Perkalian pecahan dengan bilangan bulat, bilangan bulat dengan pecahan', 14),
  (math_subject_id, 'Kelas 4', 1, 'Bilangan', '4.1.16', 'Menggunakan notasi desimal dalam pecahan dengan penyebut 10 dan 100', 15),
  (math_subject_id, 'Kelas 4', 1, 'Bilangan', '4.1.17', 'Membaca dan menulis desimal hingga 1 dan 2 angka di belakang koma', 16),
  (math_subject_id, 'Kelas 4', 1, 'Bilangan', '4.1.18', 'Membandingkan 2 desimal hingga 2 angka di belakang koma', 17),
  (math_subject_id, 'Kelas 4', 1, 'Bilangan', '4.1.19', 'Penjumlahan dan pengurangan bilangan bulat hingga 100 atau 1000', 18),
  (math_subject_id, 'Kelas 4', 1, 'Bilangan', '4.1.20', 'Perkalian dan pembagian dengan fasih dari 100 hingga 1000', 19),
  (math_subject_id, 'Kelas 4', 1, 'Analisis Data dan Peluang', '4.2.1', 'Menyelesaikan masalah dengan tabel frekuensi, diagram batang, piktograf, dan diagram garis', 20),
  (math_subject_id, 'Kelas 4', 1, 'Analisis Data dan Peluang', '4.2.2', 'Membandingkan diagram yang menggunakan data yang sama dan mengevaluasi disgram mana yang lebih sesuai dengan kebutuhan', 21),
  (math_subject_id, 'Kelas 4', 1, 'Analisis Data dan Peluang', '4.2.3', 'Memahami probabilitas ditunjukan dengan angka antara 0 dan 1,0 untuk menunjukan tidak mungkin, sekitar 1/2 mungkin dan mendekati 1 kemungkinan besar', 22),
  (math_subject_id, 'Kelas 4', 1, 'Geometri', '4.3.1', 'Mengidentifikasi bahwa satu lingkaran ada 360 derajat dan menggunaknnya sebagai satuan ukur', 23),
  (math_subject_id, 'Kelas 4', 1, 'Geometri', '4.3.2', 'Mengukur sudut menggunakan busur', 24),
  (math_subject_id, 'Kelas 4', 1, 'Geometri', '4.3.3', 'Membuat sudut dengan ukuran tertentu', 25),
  (math_subject_id, 'Kelas 4', 1, 'Geometri', '4.3.4', 'Mengklasifikaskan bangunan 2D dengan 2 garis sejajar ataun tegak lurus', 26),
  (math_subject_id, 'Kelas 4', 1, 'Geometri', '4.3.5', 'Mengenali sudut siku sebagai suatu kategori dalam mengklasifikasikan segitiga siku-siku', 27),
  (math_subject_id, 'Kelas 4', 1, 'Geometri', '4.3.6', 'Mengikuti rute peta sederhana, dengan petunjuk dan jarak yang akurat { bidang axis }', 28),
  (math_subject_id, 'Kelas 4', 1, 'Geometri', '4.3.7', 'Mengklasifikasikan bangun datar berdasarkan ciri garis yang sejajar dan garis tegak lurus atau besar dari sudut pembentuknya', 29),
  (math_subject_id, 'Kelas 4', 1, 'Geometri', '4.3.8', 'Mengenali sudut siku-siku sebagai slah satu ciri mengidentifiksi segitiga siku-siku', 30),
  (math_subject_id, 'Kelas 4', 1, 'Pengukuran', '4.4.1', 'Memperkirakan panjang dengan unit tidak baku { con : jenkal, stik eskrim, klip kertas dsb }', 31),
  (math_subject_id, 'Kelas 4', 1, 'Pengukuran', '4.4.2', 'Mengukur panjang dengan unit ukur { con cm, m }', 32),
  (math_subject_id, 'Kelas 4', 1, 'Pengukuran', '4.4.3', 'Menghitung hitung luas persegi panjang dari sisi panjang dan lebar dan menjelaskan bagaiman perkalian dapat mengukur sebuah luas bidang', 33),
  (math_subject_id, 'Kelas 4', 1, 'Pengukuran', '4.4.4', 'Menghubungkan satuan unit untuk mengukur luas', 34),
  (math_subject_id, 'Kelas 4', 1, 'Pengukuran', '4.4.5', 'Menggunakan gambar untuk menunjukksn ciri-ciri distribusi', 35),
  (math_subject_id, 'Kelas 4', 1, 'Pengukuran', '4.4.6', 'Menggunakan kubus untuk mengisi sebuah bangunan dan menggunakan lapisan atau ide perkalian { kelipatan }', 36),
  (math_subject_id, 'Kelas 4', 1, 'Pengukuran', '4.4.7', 'Menjelaskan bahwa menghitungisi atau volume terdiri dari unit kecil dan sebaliknya', 37),
  (math_subject_id, 'Kelas 5', 1, 'Bilangan', '5.1.1', 'Peserta didik dapat memahami 100.000 sebagai kumpulan dari 10 pulh ribuan dan disebut " ratusan ribu "', 0),
  (math_subject_id, 'Kelas 5', 1, 'Bilangan', '5.1.2', 'Peserta didik dapat membuat komposisi dan dekomposisi bilangan cacah berdasarkan nilai tempat puluh ribuan, ribuan, ratusan, puluhan dan  satuan', 1),
  (math_subject_id, 'Kelas 5', 1, 'Bilangan', '5.1.3', 'Peserta didik dapat melakukan menggunakan startegi pemulatan ke puluhan terdekat untulk menyelesaikan penjumlahan dan pengurangan', 2),
  (math_subject_id, 'Kelas 5', 1, 'Bilangan', '5.1.4', 'Peserti didik dapat melakukan perkalian dan pembagian { 2-digit denga 2-digit', 3),
  (math_subject_id, 'Kelas 5', 1, 'Bilangan', '5.1.5', 'Peserta didik dapat menyeleasikan masalah yang berkaitan dengan uang', 4),
  (math_subject_id, 'Kelas 5', 1, 'Bilangan', '5.1.6', 'Peserta didik dapat meemhami bahwa faktor persekutuan adalah faktor-faktor yang sama yang dapat membagi habis dua bilangan atau lebih', 5),
  (math_subject_id, 'Kelas 5', 1, 'Bilangan', '5.1.7', 'Peserta didik dapat memahami bahwa kelipatan persekutuan adalah kelipatan dari suatu bilangan yang sama dengan kelipatan lainnya.', 6),
  (math_subject_id, 'Kelas 5', 1, 'Bilangan', '5.1.8', 'Peserta didik dapat memaknai pecahan campuran adalah gabungan  dri bilangan bulat dan pecahan biasa', 7),
  (math_subject_id, 'Kelas 5', 1, 'Bilangan', '5.1.9', 'Peserta didik dapat menggunakan pecahan senilai { persepuluhan atau perseratusan } untuk mengubah pecahan  biasa atau campuran ke pecahan desimal', 8),
  (math_subject_id, 'Kelas 5', 1, 'Bilangan', '5.1.10', 'Peserta didik dapat menggunakan garis bilangan atau fraction chart untuk membandingkan dan mengurutkan pecahan', 9),
  (math_subject_id, 'Kelas 5', 1, 'Bilangan', '5.1.11', 'Peserta didik dapat melakukan penjumlahan antara pecahan berpenyebut sama dan atau berpenyebut berbeda dengan menggunakan pemahaman tentang pecahan senilai', 10),
  (math_subject_id, 'Kelas 5', 1, 'Aljabar', '5.2.1', 'Peserta didik dapat menemukan hubungan antara operasi hitung penjumlahan dan pengurangan pada bilangan cacah sampai 1000', 11),
  (math_subject_id, 'Kelas 5', 1, 'Aljabar', '5.2.2', 'Peserta didik dapat menemukan hungan antara operasi hitung perkalian dan pembagian padpa bilangan cacah sampai dengan 1000', 12),
  (math_subject_id, 'Kelas 5', 1, 'Pengukuran', '5.3.1', 'Peserta didik dapat memahami bahwa keliling dapat dikatakan sebagai jarak minimal yang diperlukan untuk mengelilingi/mengitari bangun datar tersebut sebanyak satu putaran', 13),
  (math_subject_id, 'Kelas 5', 1, 'Pengukuran', '5.3.2', 'Peserta didik dapat menunjukan bahwa luas adalah banyaknya persegi satuan yang menutupi daerah bangun datar  yang ditunjukkan', 14),
  (math_subject_id, 'Kelas 5', 1, 'Pengukuran', '5.3.3', 'Peserta didik dapat memaknai satuan-satuan waktu', 15),
  (math_subject_id, 'Kelas 5', 1, 'Pengukuran', '5.3.4', 'Peserta didik dapat menghitung durasi waktu dari sebuah kegiatan', 16),
  (math_subject_id, 'Kelas 5', 1, 'Pengukuran', '5.3.5', 'Peserta didik dapat memaknai sudut sebagai daerah yang dibentuk oleh dua sinar atau garis yang saling berpotongan yang titik pangkalnya berimpit/ sama', 17),
  (math_subject_id, 'Kelas 5', 1, 'Pengukuran', '5.3.6', 'Peserta didik dapat menjelaskan unsur-unsur sudut dan beberapa jenis sudut', 18),
  (math_subject_id, 'Kelas 5', 1, 'Geometri', '5.4.1', 'Peserta didik dapat menunjukkan bahwa bangun ruang merupakkan bangun tiga dimensi yang mempunyai ruang/isi/voulume dan juga sisi-sisi yang membatasinya', 19),
  (math_subject_id, 'Kelas 5', 1, 'Geometri', '5.4.2', 'Peserta dapat membuat bangun ruang sederhana yang terdiri dari gabungan bangun ruang kubus dan balok dengan menggunakan snap cube dan menggambarkan penampakan gabungan bangun ruang tersebut dari atas, depan dan samping.', 20),
  (math_subject_id, 'Kelas 5', 1, 'Geometri', '5.4.3', 'Peserta didik dapat menentukan denah suatu tempat pada sistem berpetak', 21),
  (math_subject_id, 'Kelas 5', 1, 'Analisis Data dan Peluang', '5.5.1', 'Peserta didik dapat mengumpulkan data hasil pengukuran', 22),
  (math_subject_id, 'Kelas 5', 1, 'Analisis Data dan Peluang', '5.5.2', 'Peserta didik dapat mengurutkan sekumpul data', 23),
  (math_subject_id, 'Kelas 5', 1, 'Analisis Data dan Peluang', '5.5.3', 'Peserta didik dapat membandingkan data hasil pengukuran', 24),
  (math_subject_id, 'Kelas 5', 1, 'Analisis Data dan Peluang', '5.5.4', 'Peserta didik dapat menyajikan data hasil pengukuran kke dalam bentuk tabel frekuensi, diagram batang, diagram garis, diagram gambar', 25),
  (math_subject_id, 'Kelas 6', 1, 'Bilangan', '6.1.1', 'Peserta didik dapat memahami 100.000 sebagai kumpulan dari 10 puluhan ribu dan disebut " ratusan ribu"', 0),
  (math_subject_id, 'Kelas 6', 1, 'Bilangan', '6.1.2', 'Peserta didik dapat membuat komposisi dan dekomposisi bilangan cacah berdasarkan nilai tempat ratusan ribu,puluhan ribu, ribuan, ratusan, puluhan, dan satuan', 1),
  (math_subject_id, 'Kelas 6', 1, 'Bilangan', '6.1.3', 'Peserta didik dapat melakukan menggunakan strategi pembulatan ke puluhan terdekat untuk menyelesaikan penjumlahan dan pengurangan', 2),
  (math_subject_id, 'Kelas 6', 1, 'Bilangan', '6.1.4', 'Peserta didik dapat melakukkan perkalian dan pembagian {  3-digit dengan 2-digit }', 3),
  (math_subject_id, 'Kelas 6', 1, 'Bilangan', '6.1.5', 'Peserta didik dapat menyelsaikan masalah yang berkaitan dengan uang', 4),
  (math_subject_id, 'Kelas 6', 1, 'Bilangan', '6.1.6', 'Peserta didik dapat memahami bahwa faktor persekutuan terbesar adalah faktor yang paling besar yang dapat membagi habis dua bilangan atau lebih', 5),
  (math_subject_id, 'Kelas 6', 1, 'Bilangan', '6.1.7', 'Peserta didik dapat memahami bahwa kelipatan persekutuan terbesar adalah kelipatan yang sama dari dua bilangan atau lebih yang nilainya paling kecil', 6),
  (math_subject_id, 'Kelas 6', 1, 'Bilangan', '6.1.8', 'Peserta didik dapat memaknai pecahan campuran adalah gabungan dari bilangan bulat dan pecahan biasa', 7),
  (math_subject_id, 'Kelas 6', 1, 'Bilangan', '6.1.9', 'Peserta didik dapat menggunakan pecahan senilai { persepuluhan dan perseratuasan } untuk mengubah pecahan biasa atau campuran ke pecahan desimal', 8),
  (math_subject_id, 'Kelas 6', 1, 'Bilangan', '6.1.10', 'Peserta didik dapat menggunakan place value grid untuk membandingkan dan mengurutkan pecahan desimal', 9),
  (math_subject_id, 'Kelas 6', 1, 'Bilangan', '6.1.11', 'Peserta didik dapat melakukkan penjumlahan antara pecahan berpenyebut sama dan atau berpenyebut berbeda dengan menggunakan pemahaman tentang pecahan senilai', 10),
  (math_subject_id, 'Kelas 6', 1, 'Bilangan', '6.1.12', 'Peserta didik dapat memahami bahwa perkalian pecahan dengan bilangan asli sebagai pembagian berulang dari pecahan yang dimaksud', 11),
  (math_subject_id, 'Kelas 6', 1, 'Aljabar', '6.2.1', 'Peserta didik dapat menggunakan strategi perkalian dan pembagian dalam mengembangkan pola bilangan', 12),
  (math_subject_id, 'Kelas 6', 1, 'Aljabar', '6.2.2', 'Peserta didik dapat memahami rasio sebagai sebuah cara yang dapat menunjukkan perbandingan sederhana dua nilai atau lebih dari besaran yang memiliki satuan yang sama atau sejenis', 13),
  (math_subject_id, 'Kelas 6', 1, 'Aljabar', '6.2.3', 'Peserta didik dapat memahami bahwa proporsi adalah suatu kalimat yang menyatakan bahwa dua perbandingan/ rasio bernilai sama', 14),
  (math_subject_id, 'Kelas 6', 1, 'Pengukuran', '6.3.1', 'Peserta didik dapat memahami bahwa keliling dapat dikatakan sebagai jarak minimal yang diperlukkan untuk mengelilingi mengitari bangun datar tersebut sebanyak satu putaran', 15),
  (math_subject_id, 'Kelas 6', 1, 'Pengukuran', '6.3.2', 'Peserta didik dapat memahami bahwa luas adalah banyaknya persegi satuan yang menutupi daerah bangun datar yang ditunjukkan', 16),
  (math_subject_id, 'Kelas 6', 1, 'Pengukuran', '6.3.3', 'Peserta didik dapat menghitung durasi waktu dari sebuah kegiatan', 17),
  (math_subject_id, 'Kelas 6', 1, 'Pengukuran', '6.3.4', 'Peserta didik dapat memahami bahwa derajat ukuran sudut yang dapat dibentuk pada sebuah bilanga datar, menggambarkan 1/360 dari sebuah putaran penuh. Artinya besar 1 derajat adalah satu juring pada lingkaran yang dibagi menjadi 360 buah juring yang besarnya sama', 18),
  (math_subject_id, 'Kelas 6', 1, 'Geometri', '6.4.1', 'Peserta didik dapat membandingkan karakterisktik bangun datar dan bangun ruang melalui kegiatan pengamatan', 19),
  (math_subject_id, 'Kelas 6', 1, 'Geometri', '6.4.2', 'Peserta didik dapat menentukkan denah suatu tempat pada sistem berpetak', 20),
  (math_subject_id, 'Kelas 6', 1, 'Analisis Data dan Peluang', '6.5.1', 'Peserta didik dapat mendeskripsikan peristiwa yang mungkin akan terjadi melalui sebuah percobaan acak', 21)
  ;
end $$;